name: Validate code

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install node & pnpm
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Lint code
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
